server {
    listen 80;
    server_name _;

    # React statik dosyaları
    root /usr/share/nginx/html;
    index index.html;

    # SPA yönlendirmesi (tüm yollar index.html'e düşer)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # /api/* isteklerini backend konteynerine yönlendir.
    # 'backend' = docker-compose'daki servis adı.
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 12M;
    }
}
